
trigger: none

pool: agent-ka-bund

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World"'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/DevopsClass01'
    backendServiceArm: 'Workload_Identity_Test'
    backendAzureRmStorageAccountName: 'knsaforpipeline'
    backendAzureRmContainerName: 'knconforpipeline'
    backendAzureRmKey: 'terraform.knconforpipeline'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/DevopsClass01'
    environmentServiceNameAzureRM: 'Workload_Identity_Test'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Workload_Identity_Test'